export const Users = [
  {
    id: 1,
    profilePicture: "../assets/person/1.jpeg",
    username: "Safak Kocaoglu",
  },
  {
    id: 2,
    profilePicture: "../assets/person/2.jpeg",
    username: "Janell Shrum",
  },
  {
    id: 3,
    profilePicture: "../assets/person/3.jpeg",
    username: "Eloise Hoareau",
  },
  {
    id: 4,
    profilePicture: "../assets/person/4.jpeg",
    username: "Myu Wang",
  },
  {
    id: 5,
    profilePicture: "../assets/person/5.jpeg",
    username: "Clara Deschateaux",
  },
  {
    id: 6,
    profilePicture: "../assets/person/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "../assets/person/7.jpeg",
    username: "Paul Janson",
  },
  {
    id: 8,
    profilePicture: "../assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "../assets/person/9.jpeg",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "../assets/person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Bon weekend .",
    photo: "../assets/post/1.jpeg",
    date: "il y a 5 mins ",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "../assets/post/2.jpeg",
    date: "il y a 15 mins",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Article interessant pour être un bon salarié.",
    photo: "../assets/post/3.jpeg",
    date: "il y a 1 heure",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "../assets/post/4.jpeg",
    date: "il y a 4 heures",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "../assets/post/5.jpeg",
    date: "il y a 5 heures",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "../assets/post/6.jpeg",
    date: "il y a 1 jour",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Ne regrette pas ce que tu entreprends.",
    photo: "../assets/post/7.jpeg",
    date: "il y a 2 jours",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "../assets/post/8.jpeg",
    date: "il y a 3 jours ",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "changer le monde sois même.",
    photo: "../assets/post/9.jpeg",
    date: "il y a 5 jours",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "../assets/post/10.jpeg",
    date: "il y a 1 semaine",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
